# Generated by Django 4.2.10 on 2025-04-06 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('body_part', models.CharField(blank=True, max_length=50)),
                ('severity_scale', models.PositiveIntegerField(default=1, help_text='Scale of 1-10 for typical severity')),
                ('common_related_conditions', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='UserSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.PositiveIntegerField(choices=[(1, 'Very Mild'), (2, 'Mild'), (3, 'Moderate'), (4, 'Uncomfortable'), (5, 'Concerning'), (6, 'Severe'), (7, 'Very Severe'), (8, 'Extreme'), (9, 'Unbearable'), (10, 'Emergency')])),
                ('onset_date', models.DateField()),
                ('is_active', models.BooleanField(default=True, help_text='Whether the symptom is still present')),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_instances', to='symptoms.symptom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SymptomCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_info', models.JSONField(blank=True, default=dict, help_text='Structured additional information like age, gender, medical history')),
                ('ai_analysis', models.TextField(blank=True)),
                ('possible_conditions', models.JSONField(blank=True, default=list, help_text='List of possible conditions with confidence levels')),
                ('recommendations', models.TextField(blank=True)),
                ('emergency_level', models.BooleanField(default=False, help_text='Whether this requires emergency attention')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symptoms', models.ManyToManyField(related_name='check_sessions', to='symptoms.usersymptom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Symptom Check',
                'verbose_name_plural': 'Symptom Checks',
                'ordering': ['-created_at'],
            },
        ),
    ]
