# Generated by Django 4.2.10 on 2025-04-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='available_times',
            field=models.JSONField(default=dict, help_text='Dictionary of available time slots'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialties',
            field=models.JSONField(default=list, help_text="List of doctor's specialties"),
        ),
    ]
